const KEY='codespace_state_v1';
const defaults={profile:{name:'My Name',bio:''},app:{name:'CodeSpace',path:'Download/CodeSpace'},spaces:[],projects:[]};
let state=load();let current={view:'spaces',projectId:null,spaceId:null};
let rootHandle=null;
const HANDLE_DB='codespace_fs';
async function openHandleDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(HANDLE_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('handles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveRootHandle(h){try{const db=await openHandleDB();const tx=db.transaction('handles','readwrite');tx.objectStore('handles').put(h,'root');return new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}catch(e){console.warn(e)}}
async function getRootHandle(){try{const db=await openHandleDB();return new Promise((res,rej)=>{const tx=db.transaction('handles');const r=tx.objectStore('handles').get('root');r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}catch{return null}}
async function ensurePermission(h){if(!h)return false;try{let p=await h.queryPermission({mode:'readwrite'});if(p==='granted')return true;if(p==='prompt')p=await h.requestPermission({mode:'readwrite'});return p==='granted'}catch{return false}}
async function createDir(parent,name){return parent.getDirectoryHandle(name,{create:true})}
async function setupStorage(){if(!('showDirectoryPicker' in window)){showAccessBanner(false);return false}if(!rootHandle)rootHandle=await getRootHandle();if(rootHandle&&await ensurePermission(rootHandle)){await prepareFolders(rootHandle);showAccessBanner(false);return true}showAccessBanner(true);return false}
async function prepareFolders(root){const data=await createDir(root,'data');await createDir(data,'spaces');await createDir(data,'projects');await createDir(data,'data');await createDir(root,'metadata')}
function showAccessBanner(show){const b=document.querySelector('#fileAccessBanner');if(!b)return;b.classList.toggle('hidden',!show);const btn=document.querySelector('#grantAccess');if(btn)btn.onclick=chooseRootFolder}
async function chooseRootFolder(){if(!('showDirectoryPicker' in window)){alert('Этот браузер не поддерживает выбор папки. Для прямого доступа к Download/CodeSpace нужен Android WebView/нативное приложение.');return}try{rootHandle=await window.showDirectoryPicker({mode:'readwrite'});if(await ensurePermission(rootHandle)){await saveRootHandle(rootHandle);await prepareFolders(rootHandle);state.app.path='Выбранная папка';save();showAccessBanner(false);alert('Доступ разрешён. Папки CodeSpace созданы внутри выбранной папки.')}}catch(e){if(e.name!=='AbortError')alert('Не удалось получить доступ к папке.')}}
async function writeTextFile(dir,name,text){const h=await dir.getFileHandle(name,{create:true});const w=await h.createWritable();await w.write(text);await w.close()}
async function syncMetadata(){if(!rootHandle||!(await ensurePermission(rootHandle)))return;try{const metadata=await rootHandle.getDirectoryHandle('metadata',{create:true});await writeTextFile(metadata,'state.json',JSON.stringify(state,null,2));const data=await rootHandle.getDirectoryHandle('data',{create:true});const spaces=await data.getDirectoryHandle('spaces',{create:true});const projects=await data.getDirectoryHandle('projects',{create:true});for(const sp of state.spaces){const d=await spaces.getDirectoryHandle(sp.id,{create:true});await writeTextFile(d,'metadata.json',JSON.stringify(sp,null,2))}for(const pr of state.projects){const d=await projects.getDirectoryHandle(pr.id,{create:true});await writeTextFile(d,'metadata.json',JSON.stringify(pr,null,2))}}catch(e){console.warn('Filesystem sync failed',e)}}

const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));syncMetadata()}
function id(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function render(){let c=$('#content'); if(current.view==='spaces')c.innerHTML=spacesView();else if(current.view==='projects')c.innerHTML=projectsView();else if(current.view==='create-space')c.innerHTML=createSpaceView();else if(current.view==='create-project')c.innerHTML=createProjectView();else if(current.view==='space')c.innerHTML=spaceView();else if(current.view==='project')c.innerHTML=projectView();else if(current.view==='settings')c.innerHTML=settingsView();bind();}
function shell(title,sub){return `<h1 class="view-title">${title}</h1><p class="sub">${sub||''}</p>`}
function spacesView(){return shell('Spaces','Все пространства')+(state.spaces.length?`<div class="grid">${state.spaces.map(s=>`<article class="card"><h3>${esc(s.name)}</h3><div class="meta">${esc(s.description||'Без описания')}</div><div class="path">/spaces/${esc(state.profile.name.replace(/\s+/g,'-').toLowerCase())}/${s.id}</div><div class="row"><button class="btn secondary open-space" data-id="${s.id}">Открыть</button><button class="btn danger delete-space" data-id="${s.id}">Удалить</button></div></article>`).join('')}</div>`:'<div class="empty">Пространств пока нет.</div>')}
function projectsView(){return shell('Projects','Все проекты')+(state.projects.length?`<div class="grid">${state.projects.map(p=>`<article class="card"><h3>${esc(p.name)}</h3><div class="meta">${esc(p.description||'Без описания')}</div><div class="path">/projects/${esc(state.profile.name.replace(/\s+/g,'-').toLowerCase())}/${p.id}</div><div class="row"><button class="btn secondary open-project" data-id="${p.id}">Открыть</button><button class="btn danger delete-project" data-id="${p.id}">Удалить</button></div></article>`).join('')}</div>`:'<div class="empty">Проектов пока нет.</div>')}
function createSpaceView(){return shell('Create space','Создай пространство для файлов и папок')+form('space')}
function createProjectView(){return shell('Create project','Проект может содержать связанные пространства')+form('project')}
function form(type,obj={}){return `<form class="form" id="${type}Form"><div class="field"><label>Название</label><input name="name" required maxlength="80" value="${esc(obj.name||'')}"></div><div class="field"><label>Описание</label><textarea name="description" maxlength="500">${esc(obj.description||'')}</textarea></div>${type==='project'?`<div class="field"><label>GitHub Pages URL</label><input name="github" placeholder="https://username.github.io/repository" value="${esc(obj.github||'')}"></div>`:''}<button class="btn">Создать</button></form>`}
function spaceView(){let s=state.spaces.find(x=>x.id===current.spaceId);if(!s)return spacesView();return shell(esc(s.name),`/spaces/${state.profile.name.replace(/\s+/g,'-').toLowerCase()}/${s.id}`)+`<div class="notice">Файлы и папки этого пространства хранятся локально. На телефоне выбери корневую папку CodeSpace через «Настройки → App → Path».</div><div class="row"><button class="btn" id="newFolder">Новая папка</button><button class="btn secondary" id="uploadFile">Загрузить файл</button></div><div class="file-list" style="margin-top:18px">${s.items.length?s.items.map(i=>`<div class="file"><span>${i.kind==='folder'?'📁':'📄'} ${esc(i.name)}</span><span class="meta">/${esc(i.path||i.name)}</span></div>`).join(''):'<div class="empty">Здесь пока нет файлов.</div>'}</div>`}
function projectView(){let p=state.projects.find(x=>x.id===current.projectId);if(!p)return projectsView();let spaces=state.spaces.filter(s=>s.projectId===p.id);return shell(esc(p.name),`/projects/${state.profile.name.replace(/\s+/g,'-').toLowerCase()}/${p.id}`)+`<div class="notice">${p.github?`GitHub Pages: <a href="${esc(p.github)}" target="_blank">${esc(p.github)}</a>`:'GitHub Pages ссылка не задана.'}</div><div class="row"><button class="btn" id="projectSpace">Создать пространство</button></div><div class="grid" style="margin-top:18px">${spaces.length?spaces.map(s=>`<article class="card"><h3>${esc(s.name)}</h3><div class="path">/spaces/${esc(state.profile.name.replace(/\s+/g,'-').toLowerCase())}/${s.id}</div><button class="btn secondary open-space" data-id="${s.id}">Открыть</button></article>`).join(''):'<div class="empty">У проекта пока нет пространств.</div>'}</div>`}
function settingsView(){return shell('Settings','Профиль и параметры приложения')+`<div class="form"><h3>Profile</h3><div class="field"><label>Имя</label><input id="profileName" value="${esc(state.profile.name)}"></div><div class="field"><label>О себе</label><textarea id="profileBio">${esc(state.profile.bio)}</textarea></div><button class="btn" id="saveProfile">Сохранить профиль</button><hr style="border-color:var(--border);margin:25px 0"><h3>App</h3><div class="switch"><span>rename</span><button class="btn secondary" id="renameApp">Изменить</button></div><div class="switch"><span>path</span><button class="btn secondary" id="pathApp">Выбрать</button></div><div class="meta">Текущий путь: ${esc(state.app.path)}</div></div>`}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{current={view:b.dataset.view};$('#sideMenu').classList.remove('open');render()});document.querySelectorAll('.open-space').forEach(b=>b.onclick=()=>{current={view:'space',spaceId:b.dataset.id};render()});document.querySelectorAll('.open-project').forEach(b=>b.onclick=()=>{current={view:'project',projectId:b.dataset.id};render()});document.querySelectorAll('.delete-space').forEach(b=>b.onclick=()=>{if(confirm('Удалить пространство?')){state.spaces=state.spaces.filter(s=>s.id!==b.dataset.id);save();render()}});document.querySelectorAll('.delete-project').forEach(b=>b.onclick=()=>{if(confirm('Удалить проект и связанные пространства?')){state.projects=state.projects.filter(p=>p.id!==b.dataset.id);state.spaces=state.spaces.filter(s=>s.projectId!==b.dataset.id);save();render()}});let sf=$('#spaceForm');if(sf)sf.onsubmit=e=>{e.preventDefault();let f=new FormData(sf);state.spaces.push({id:id(),name:f.get('name'),description:f.get('description'),projectId:null,items:[]});save();current.view='spaces';render()};let pf=$('#projectForm');if(pf)pf.onsubmit=e=>{e.preventDefault();let f=new FormData(pf);state.projects.push({id:id(),name:f.get('name'),description:f.get('description'),github:f.get('github'),createdAt:Date.now()});save();current.view='projects';render()};if($('#projectSpace'))$('#projectSpace').onclick=()=>{current.view='create-space';render()};if($('#saveProfile'))$('#saveProfile').onclick=()=>{state.profile.name=$('#profileName').value.trim()||'My Name';state.profile.bio=$('#profileBio').value;save();render()};if($('#renameApp'))$('#renameApp').onclick=()=>{let n=prompt('Новое название папки приложения:',state.app.name);if(n){state.app.name=n;save();render()}};if($('#pathApp'))$('#pathApp').onclick=()=>chooseRootFolder();if($('#newFolder'))$('#newFolder').onclick=()=>{let n=prompt('Название папки:');if(n){let s=state.spaces.find(x=>x.id===current.spaceId);s.items.push({kind:'folder',name:n,path:n});save();render()}};if($('#uploadFile'))$('#uploadFile').onclick=()=>uploadToSpace()}
async function uploadToSpace(){let input=document.createElement('input');input.type='file';input.multiple=true;input.onchange=()=>{let s=state.spaces.find(x=>x.id===current.spaceId);for(const f of input.files)s.items.push({kind:'file',name:f.name,path:f.webkitRelativePath||f.name,size:f.size});save();render()};input.click()}
$('#menuBtn').onclick=()=>$('#sideMenu').classList.toggle('open');$('#settingsBtn').onclick=()=>{current.view='settings';render()};render();setupStorage();
